source 'http://rubygems.org'

gem 'cinch', '2.1.0'
gem 'rest-client', '1.6.7'
gem 'nokogiri', '1.5.11'
gem 'youtube_it', '2.1.13'
gem 'alchemist', '0.1.5'
gem 'em-synchrony', '1.0.3'
gem 'ruby-mpd', '0.2.1'
gem 'typhoeus', '0.6.2'
gem 'twitter', '4.6.2'
gem 'tweetstream', '2.5.0'
gem 'open4', '1.3.3'
gem 'trollop', '1.16.2'
gem 'ruby-youtube-dl', :github => 'bnmrrs/ruby-youtube-dl', :branch => 'master'
gem 'vlcrc', :github => 'ssedano/vlcrc', :branch => 'master'
gem 'mplayer-ruby', :github =>'ssedano/mplayer-ruby', :branch=> 'master'
gem 'after_the_deadline', :github => 'ssedano/after_the_deadline', :branch => 'master'
