source "http://rubygems.org"

gem "cinch"
gem "rest-client"
gem "ruby-youtube-dl"
gem "mplayer-ruby"
gem "youtube_it"
gem "vlcrc"
gem "alchemist"
gem "em-synchrony"
gem "ruby-mpd"
gem 'typhoeus'
gem "goospell"
gem "twitter"
gem "tweetstream"
gem "nokogiri"
